services:
  db:
    image: postgres:16
    container_name: uniplan-db
    environment:
      POSTGRES_DB: uniplan
      POSTGRES_USER: uniplan
      POSTGRES_PASSWORD: uniplan
    ports:
      - "5432:5432"
    volumes:
      - uniplan-db:/var/lib/postgresql/data

volumes:
  uniplan-db:
